services:

  postgres:
    image: postgres:16

    container_name: bus_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


  rabbitmq:
    image: rabbitmq:3-management

    container_name: bus_rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  auth_service:
    build: ./services/auth_service

    container_name: auth_service

    env_file:
      - ./services/auth_service/.env

    ports:
      - "8000:8000"

    volumes:
      - ./services/auth_service:/app

    depends_on:
      - postgres
      - rabbitmq


  # transport_service:
  #   build: ./services/transport_service

  #   container_name: transport_service

  #   depends_on:
  #     - postgres
  #     - rabbitmq


  # reservation_service:
  #   build: ./services/reservation_service

  #   container_name: reservation_service

  #   depends_on:
  #     - postgres
  #     - rabbitmq


  # notification_service:
  #   build: ./services/notification_service

  #   container_name: notification_service

  #   depends_on:
  #     - rabbitmq


volumes:
  postgres_data: